function sortearPresente() {
    const links = [
       'https://s.shopee.com.br/40PVIhO1PA',
            'https://s.shopee.com.br/2LHHJisTCq',
            'https://s.shopee.com.br/2Axr7T5R4K',
            'https://s.shopee.com.br/9zgiRuenpD',
            'https://s.shopee.com.br/30Wy75rB4O',
            'https://s.shopee.com.br/LWCwDw7bm',
            'https://s.shopee.com.br/g93KzD0f6',
            'https://s.shopee.com.br/7036sfMwfA',
            'https://s.shopee.com.br/qSTXMxE0X',
            'https://s.shopee.com.br/5AbShP5AQ7',
            'https://s.shopee.com.br/9pNIG10Cmz',
            'https://s.shopee.com.br/50I2VA8aMr',
            'https://s.shopee.com.br/AUcz3QSHfn',
            'https://s.shopee.com.br/4VLluS9ZJg',
            'https://s.shopee.com.br/3VTEikS5QZ',
            'https://s.shopee.com.br/9pNIGPPE8S',
            'https://s.shopee.com.br/5pr9V5deBb',
            'https://s.shopee.com.br/7UzNUIYcFw',
            'https://s.shopee.com.br/4L2LiVnmXS',
            'https://s.shopee.com.br/6fQGUqdgfi',
            'https://s.shopee.com.br/6ATztynexC',
            'https://s.shopee.com.br/5fXjJ7izuD',
            'https://s.shopee.com.br/g93LyfIqP',
            'https://s.shopee.com.br/7036thAMPX',
            'https://s.shopee.com.br/7UzNXGHHPT',
            'https://s.shopee.com.br/1B5K16qHRP',
            'https://s.shopee.com.br/AKJYvzCaXk',
            'https://s.shopee.com.br/VpdDwissy',
            'https://s.shopee.com.br/2AxrDAytkb',
            'https://s.shopee.com.br/7KfxMm2n7R',
            'https://s.shopee.com.br/7zveA3PvAA',
            'https://s.shopee.com.br/7fInlVL6cL',
            'https://s.shopee.com.br/1qL0ozBBLT',
            'https://s.shopee.com.br/1B5K1ouzDf',
            'https://s.shopee.com.br/VpdEdMhbZ',
            'https://s.shopee.com.br/4VLm05MvP4',
            'https://s.shopee.com.br/3L9oc2BT6G',
            'https://s.shopee.com.br/4VLm0FJ5jn',
            'https://s.shopee.com.br/1ViAQowjz0',
            'https://s.shopee.com.br/6pjgmptfLL',
            'https://s.shopee.com.br/8zoBMs1K5b',
            'https://s.shopee.com.br/7fInma7JEN',
            'https://s.shopee.com.br/30WyE1k7TQ',
            'https://s.shopee.com.br/7AMXBn5uch',
            'https://s.shopee.com.br/3VTEp9dRhr',
            'https://s.shopee.com.br/4L2LojzK3H',
            'https://s.shopee.com.br/7AMXEaSQJU',
            'https://s.shopee.com.br/6V6qROKwRS',
            'https://s.shopee.com.br/8pUlDiOrXS',
            'https://s.shopee.com.br/9pNIPbAYyM',
            'https://s.shopee.com.br/3fmf4JApS5',
            'https://s.shopee.com.br/6pjgqCshJp',
            'https://s.shopee.com.br/BCmtyvL6e',
            'https://s.shopee.com.br/1LOkIBG5Ia',
            'https://s.shopee.com.br/6KnQFSuctj',
            'https://s.shopee.com.br/9zgicG12eK',
            'https://s.shopee.com.br/9f3sDg1qY3',
            'https://s.shopee.com.br/1g1ah1ml2W',
            'https://s.shopee.com.br/qSThWxzT3',
            'https://s.shopee.com.br/5Kut3qjyio',
            'https://s.shopee.com.br/6pjgqdhW4D',
            'https://s.shopee.com.br/8fBL29ORiw',
            'https://s.shopee.com.br/AKJZ1I7HVq',
            'https://s.shopee.com.br/1qL0tgzIu4',
            'https://s.shopee.com.br/4pycTG3mxl',
            'https://s.shopee.com.br/6V6qSRH614',
            'https://s.shopee.com.br/7zveFEJEvP',
            'https://s.shopee.com.br/10ltuRD4RN',
            'https://s.shopee.com.br/3L9oglymYv',
            'https://s.shopee.com.br/40PVU3PlIA',
            'https://s.shopee.com.br/9pNIQo6fJP',
            'https://s.shopee.com.br/10ltudH5iV',
            'https://s.shopee.com.br/1B5K6zsqKF',
            'https://s.shopee.com.br/5VEJH0AjfK',
            'https://s.shopee.com.br/8UruqZtEMl',
            'https://s.shopee.com.br/g93WDqlaU',
            'https://s.shopee.com.br/5Kut4qGbQZ',
            'https://s.shopee.com.br/7pcE3Yqiud',
            'https://s.shopee.com.br/1g1aiKBZNA',
            'https://s.shopee.com.br/LWD7tgqVp',
            'https://s.shopee.com.br/3VTEtkcZmK',
            'https://s.shopee.com.br/4pycUEWgyw',
            'https://s.shopee.com.br/qSTka0hZR',
            'https://s.shopee.com.br/LWD9gsecW',
            'https://s.shopee.com.br/9f3sGtZqzN',
            'https://s.shopee.com.br/40PVWVUMEQ',
            'https://s.shopee.com.br/5Kut76YMdC',
            'https://s.shopee.com.br/2AxrLK1YPN',
            'https://s.shopee.com.br/4VLm7gqeRt',
            'https://s.shopee.com.br/5Kut7IXutT',
            'https://s.shopee.com.br/6V6qVW9r9h',
            'https://s.shopee.com.br/8UrutG0hCR',
            'https://s.shopee.com.br/6fQGhwxBtV',
            'https://s.shopee.com.br/9zgig7EUWB',
            'https://s.shopee.com.br/LWDHsz7Hu',
            'https://s.shopee.com.br/1B5KHXx71Y'
    ];

   
    const linkSorteado = links[Math.floor(Math.random() * links.length)];

    window.open(linkSorteado, "_blank");
}

document.addEventListener("DOMContentLoaded", () => {
    const botaoSortear = document.getElementById("btnSortear");
    botaoSortear.addEventListener("click", sortearPresente);
});